### ISSUE TITLE
Phones: Lightbox object captions

### ISSUE THREAD

**Issue by halfempty** [stillmuseum/worksonpaper#100]
These currently are hidden on phones.

**Comment by halfempty** [comment]
@dabernathy89 Dan, regarding the object lightboxes:

Currently, when the display gets down phone-sized display, the object caption info is simply hidden and the iframe containing the image is set to fill the available space.

What we'd like to do is add a toggle of some kind, allowing users to switch between image and caption views. The toggle would hide one and show the other. When the display is enlarged to the next breakpoint, the toggle would hide and the elements would return to their current configuration.

**Comment by dabernathy89** [comment]
Should be pretty straightforward - I think middle of next week is doable.

**Comment by dabernathy89** [comment]
I'm sure y'all will have some recommendations for styling on this, but here's a demo of it:

http://pubs.clyffordstillmuseum.org/worksonpaperdev/first-abstractions/#object-1-2011-27

**Comment by halfempty** [comment]
@dabernathy89 Great! What about something like this:

![image](https://cloud.githubusercontent.com/assets/775543/20684576/3176a7ce-b576-11e6-9af6-0e377135c6e4.png)

(I realize this layout will likely mean re-jiggering the placement of the "close" button in the markup.)

**Comment by dabernathy89** [comment]
Sure, that's doable.

**Comment by swambold6** [comment]
Yay!

**Comment by swambold6** [comment]
@dabernathy89 @halfempty Looking good. Couple of questions...

Do we have the ability to change the info icon? Can we get the close X to be on the same line as the other icons? (Leave it on the right side and the other two on the left side though!)

**Comment by dabernathy89** [comment]
@swambold6 are you ok with the info icon in the mockup @halfempty provided above?

**Comment by halfempty** [comment]
@dabernathy89 Btw the icon I used was from Genericons

**Comment by dabernathy89** [comment]
better? http://pubs.clyffordstillmuseum.org/worksonpaperdev/first-abstractions/#object-1-2011-27

**Comment by halfempty** [comment]
@dabernathy89 Fantastic! I would like to tweak the styling -- maybe easiest for me to pop just into the CSS?

**Comment by dabernathy89** [comment]
@halfempty let me push up what I have to Github really quick

**Comment by dabernathy89** [comment]
@halfempty sorry meant to mention the github repo is now synced with the dev site

**Comment by halfempty** [comment]
@dabernathy89 Okay, I'm done with the styling. But hey, I've noticed one functional bug. In short, the view needs to be reset when going from small-screen to large-screen. To reproduce:

- Size-down your window, to get the mobile view;
- Click the "info" icon, to show the caption;
- Size-up your window, to desktop view;

The result is:

![image](https://cloud.githubusercontent.com/assets/775543/21241101/c797ca3e-c2d3-11e6-9040-c0a6f6b14400.png)

I've a function in the JS that I use to test if we're in responsive view or not (created for just these kinds of situations). Maybe that can help? Happy to connect on it if need be.

**Comment by halfempty** [comment]
@dabernathy89 Thanks! The class on the "i" icon remained, so I've tweaked.
