### ISSUE TITLE
Replace Work Display Measurement column from new spreadsheet

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/worksonpaper#103]
@halfempty 

New spreadsheet here:
Dropbox (ClyffordStillMuseum)/Works on Paper Digital Catalogue/20161028_WOP_DigitalPub.xlsx

Column H has updated "inches" to "in." to be consistent with art object citations in books. Importing this column of data should replace the Work Display Measurement #1 field in WP.

I'm not 100% confident in the data in the rest of the doc (save for the Unique IDs ... those have not changed). So a full import of the entire data set should be avoided. If a full import needs to happen, let me know so I can comb the spreadsheet again). Of course let me know if none of this makes sense.

**Comment by halfempty** [comment]
Done
