### ISSUE TITLE
Is there a way to link to lightbox images from within description text?

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/worksonpaper#104]
@halfempty 

For example, PP-137 is referenced in the second paragraph on this page:
http://pubs.clyffordstillmuseum.org/worksonpaperdev/new-york-city/

Is there any way to hyperlink PP-137 to it's lightbox object view? (There are a handful of these instances.)

**Comment by halfempty** [comment]
@swambold6 Not easily, but possible if it's important.

**Comment by halfempty** [comment]
@swambold6 Can you specify the locations of each of these / which object they should open?

**Comment by halfempty** [comment]
@dabernathy89 Dan, Sarah would like to be able to trigger the object lightboxes from within body copy. I'm thinking maybe a shortcode, where Sarah specifies the slug of the Object she wishes to link to? There are a few of considerations, I can think of:

First is that the correct object data needs to be output onto the page. In existing cases this is done via an array called `$objectstash`. So it will need to populate this.

Second is link itself. The lightbox links contain some specific markup to make them work, including a `data-slug` attribute.

Third is the JS, which acts on the links.

**Comment by dabernathy89** [comment]
Makes sense. Timeline on this one?

**Comment by dabernathy89** [comment]
Also thinking middle of next week for this one

**Comment by dabernathy89** [comment]
Got this working - here is an example:

http://pubs.clyffordstillmuseum.org/worksonpaperdev/first-abstractions/

I used an object that isn't displayed on the page already just to demonstrate that it's pulling in the details correctly.

**Comment by halfempty** [comment]
@dabernathy89 Great! What about something like this:

![image](https://cloud.githubusercontent.com/assets/775543/20684576/3176a7ce-b576-11e6-9af6-0e377135c6e4.png)

(I realize this layout will likely mean re-jiggering the placement of the "close" button in the markup.)

**Comment by halfempty** [comment]
@swambold6 Could you give Dan a list of where you want these internal links?

**Comment by swambold6** [comment]
Will work on this and get back to you...

**Comment by swambold6** [comment]
@dabernathy89 @halfempty Apologies for my delay. Here is the list (there may be one more to add to this...I'll solve the mystery this morning...)

http://pubs.clyffordstillmuseum.org/worksonpaperdev/the-figure/

- PP-4 (in the first paragraph) should open
http://pubs.clyffordstillmuseum.org/worksonpaperdev/the-figure/#object-1-2011-1443

___

http://pubs.clyffordstillmuseum.org/worksonpaperdev/first-abstractions/

- Remove the sample link in the first paragraph

- PH-536 (in the last paragraph on the page) should open
http://pubs.clyffordstillmuseum.org/worksonpaperdev/first-abstractions/#object-1-2011-811

- PP-128 (same paragraph, last one on page)
http://pubs.clyffordstillmuseum.org/worksonpaperdev/first-abstractions/#object-1-2011-1566

____

http://pubs.clyffordstillmuseum.org/worksonpaperdev/the-richmond-oils-on-paper/

- PH-488 (first paragraph) should open
http://pubs.clyffordstillmuseum.org/worksonpaperdev/the-richmond-oils-on-paper/#object-1-2011-769

- PH-536 (first paragraph) should open
http://pubs.clyffordstillmuseum.org/worksonpaperdev/first-abstractions/#object-1-2011-811

- PH-547 (second paragraph)
http://pubs.clyffordstillmuseum.org/worksonpaperdev/the-richmond-oils-on-paper/#object-1-2011-822

- PH-535 (second paragraph)
http://pubs.clyffordstillmuseum.org/worksonpaperdev/the-richmond-oils-on-paper/#object-1-2011-810

____

http://pubs.clyffordstillmuseum.org/worksonpaperdev/san-francisco/

- PH-479 (second paragraph)
http://pubs.clyffordstillmuseum.org/worksonpaperdev/san-francisco/#object-fa1976-92

- PH-455 (second paragraph)
http://pubs.clyffordstillmuseum.org/worksonpaperdev/san-francisco/#object-1-2011-741

**Comment by swambold6** [comment]
@dabernathy89 @halfempty One more:

http://pubs.clyffordstillmuseum.org/worksonpaperdev/new-york-city/
PP-136 (second paragraph) should link to:
http://pubs.clyffordstillmuseum.org/worksonpaperdev/new-york-city/#object-1-2011-1574

**Comment by dabernathy89** [comment]
I'll work through these ASAP.

**Comment by dabernathy89** [comment]
These are all linked now. @swambold6 @halfempty

**Comment by swambold6** [comment]
@dabernathy89 @halfempty Everything looks good! Hooray! And thanks!
