### ISSUE TITLE
Typestyles on TOC / homepage

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/worksonpaper#106]
@halfempty I know I owe you an updated suite of INDD docs (which will include proper typestyles). But just so it's on your radar, the iPad size is showing the H2s at different sizes like it was on the desktop display. Like I said, I owe you INDD docs, but I did want to flag it for you now since it will be an A priority item.

**Comment by halfempty** [comment]
@swambold6 Not sure I understand? Looking at the homepage at that size we have...

"Table of Contents" (H2) - 32px
Page titles (H3's and Menu Items) - 24px
Paragraphs - 20px

**Comment by swambold6** [comment]
@halfempty Is it possible that the follow are all coded as paragraph style then?

Exhibition
The Draftsman
Landscape
The Figure
First Abstractions
The Richmond Oils
San Francisco
New York City
The Late Drawings
Acknowledgments
About

![screen shot 2016-10-31 at 12 23 03 pm](https://cloud.githubusercontent.com/assets/7491703/19866174/b8bc1d18-9f64-11e6-9624-ff37e7a0d9ce.png)

**Comment by halfempty** [comment]
@swambold6 Refresh your cache?

**Comment by swambold6** [comment]
@halfempty I've created a clean, fresh INDD doc here:
https://www.dropbox.com/s/yuqdvc84u0cavq4/20161028_WorksOnPaper.indd?dl=0

I've cleaned up the 1024 size. Please take a look and let me know if this includes all the information you want. If so, I'll create layouts for each of the breakpoints.

(just got your comment, will refresh now...)

**Comment by swambold6** [comment]
@halfempty I'm seeing no changes on this end. Looking at it in different browsers would do it, wouldn't it? (I just checked it in Firefox.)

**Comment by halfempty** [comment]
@swambold6 Here's what I'm seeing...

![image](https://cloud.githubusercontent.com/assets/775543/19866310/b2bd318c-9f6d-11e6-960b-2a88a7491bca.png)

**Comment by swambold6** [comment]
@halfempty Well, what other guesses do you have? It's displaying obviously different typesizes on every machine I've viewed it on for at least a week... I'm stumped.

**Comment by halfempty** [comment]
@swambold6 Your screenshot is of the live site, not dev

**Comment by swambold6** [comment]
@halfempty Cool. Thanks!
