### ISSUE TITLE
Salon Wall text is appearing in objects in Gallery 9

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/worksonpaper#108]
@halfempty Must've missed this on the dev site, but "Salon Wall" should not be visible. Not sure if that's in an incorrect column, or if it's just not hidden in Gallery 9 objects. I've clicked around and am not seeing anywhere else where this is visible. Hopefully an easy fix.

**Comment by halfempty** [comment]
@swambold6 Not sure I understand. Take a screenshot?

**Comment by swambold6** [comment]
Sorry...forgot to attach it...

![screen shot 2016-10-31 at 9 45 30 am](https://cloud.githubusercontent.com/assets/7491703/19860714/70fc6fe2-9f4f-11e6-8451-92779630abe5.png)

**Comment by halfempty** [comment]
@swambold6 Not sure how it got there, but it was in the Lending Credit field. Removed.
