### ISSUE TITLE
New photo in essay needs to be formatted correctly

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/worksonpaper#109]
We've added a new inline image to the essay page (http://pubs.clyffordstillmuseum.org/worksonpaperdev/how-to-render-the-sublime/). The image needs to be formatted correctly or have styles applied consistent with the treatment of the other inline images.

![screen shot 2016-11-14 at 11 45 49 am](https://cloud.githubusercontent.com/assets/7491703/20277905/daf877e0-aa5f-11e6-8aea-406ead317546.png)

**Comment by halfempty** [comment]
Done
