### ISSUE TITLE
PhotoSwipe

### ISSUE THREAD

**Issue by halfempty** [stillmuseum/worksonpaper#11]
Probably lots to talk about / workout about this, but here's one to start.

When you trigger PhotoSwipe it opens its own lightbox window and the zooming happens within there. Our design, though, calls for us to already be in something of a lightbox. Is this too many lightboxes?

Rudimentary demo:

http://pubs.clyffordstillmuseum.org/worksonpaperdev/object/1-2011-597/

**Comment by swambold6** [comment]
>> Is this too many lightboxes?
Yes.

**Comment by halfempty** [comment]
@swambold6 White BG on the photoswipe:

http://pubs.clyffordstillmuseum.org/worksonpaperdev/object/1-2011-597-2/

**Comment by halfempty** [comment]
@swambold6 now with the figure drawing:

http://pubs.clyffordstillmuseum.org/worksonpaperdev/object/1-2011-597-2/

Two questions: 
How do you feel about the white against the dark grey?
And then, how do you feel about the white "zoom" lightbox?

**Comment by swambold6** [comment]
I don't like the white against the dark grey. I mind the white less (though, still not a fan) in the zoom lightbox but the opacity (ie lack of transparency) doesn't communicate that to close the view you simply click the white.

With so little background showing, if we did dark gray on the image and transparent background on the zoom, is it going to be glaringly obvious that it's not seamless??

**Comment by swambold6** [comment]
Posted updated PDF to Object Views thread.

**Comment by halfempty** [comment]
@swambold6 Okay cool. Closing this thread.
