### ISSUE TITLE
Download and store links

### ISSUE THREAD

**Issue by halfempty** [stillmuseum/worksonpaper#113]
**@swambold6 says:**

> Add download links and link to store (when POD is available) to site (I’m thinking in the footer rather than a whole new page

**Comment by swambold6** [comment]
@halfempty Downloads are now ready to be posted!!! !!! !!! !!!!!!!! !!! !!!

Here:
<img width="819" alt="screen shot 2017-01-13 at 1 43 27 pm" src="https://cloud.githubusercontent.com/assets/7491703/21945056/732a4c0e-d996-11e6-9da0-cca18a84d83d.png">

I did not find a fleshed out design in my mockups for how to handle these. I'm inclined to suggest a button in the footer, but would be happy to not suggest anything if you have a suggestion. Let me know.

**Comment by swambold6** [comment]
@halfempty Uploading new (re- color corrected) files now.
