### ISSUE TITLE
Location in exhibition appearing on objects

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/worksonpaper#115]
@halfempty We had a similar issue with the Salon Wall in the last gallery I think... "Archives case" appears on several objects (in the First Abstractions gallery) and shouldn't be appearing.

http://pubs.clyffordstillmuseum.org/worksonpaper/first-abstractions/#object-1-2011-1428

![screen shot 2016-11-21 at 2 41 55 pm](https://cloud.githubusercontent.com/assets/7491703/20501902/fb876360-aff8-11e6-88e8-cfd143e02aed.png)

**Comment by halfempty** [comment]
@dabernathy89 Can you investigate?

**Comment by dabernathy89** [comment]
So it looks like this is just set in the 'Lending Credit' custom field on the objects. Should the lending credit not appear at all, or do we just need to clear out any instances where it is set to 'Archives case'?

**Comment by halfempty** [comment]
@swambold6 It sounds like you can just remove 'Archives case' from the 'Lending Credit' custom field. Cool? Or, if you'd like us to do it, pls clarify where it should be removed and where it should stay. Thanks!

**Comment by swambold6** [comment]
@halfempty These two need Lending Credits to appear. Everywhere else it should NOT appear:

http://pubs.clyffordstillmuseum.org/worksonpaper/the-richmond-oils-on-paper/#object-phx-13
http://pubs.clyffordstillmuseum.org/worksonpaper/san-francisco/#object-fa1976-92

Note that location is showing on these objects as well, and should be removed.

**Comment by swambold6** [comment]
@halfempty Text should appear as follows...

http://pubs.clyffordstillmuseum.org/worksonpaper/the-richmond-oils-on-paper/#object-phx-13
PHX-13
(Fear)

1945	
oil on paper	
25 3/4 x 19 1/2 in. (65.4 x 49.5 cm)	
Private Collection, Denver, Colorado.

Purchased by Betty Parsons from Still and exhibited in the Institute of Contemporary Art’s exhibition “The Decisive Years,” Philadelphia, 1965.


http://pubs.clyffordstillmuseum.org/worksonpaper/san-francisco/#object-fa1976-92
PH-479
1948	
gouache on paper	
28 7/8 x 22 in. (73.3 x 55.9 cm)	
Collection of the New Jersey State Museum, Trenton, New Jersey. Gift of Mr. and Mrs. L.B. Wescott.

Exhibited at the Marlborough-Gerson Gallery, New York, 1969–70

**Comment by halfempty** [comment]
@swambold6 Okay, I've hacked this into the code.

Now, Yes Lending Credit on these:
http://pubs.clyffordstillmuseum.org/worksonpaperdev/the-richmond-oils-on-paper/#object-phx-13
http://pubs.clyffordstillmuseum.org/worksonpaperdev/san-francisco/#object-fa1976-92

No lending credit elsewhere, for example here:
http://pubs.clyffordstillmuseum.org/worksonpaperdev/first-abstractions/#object-1-2011-1428

(I was just reading about these kinds of hacks. They're called "technical debt". In this case I think we'll be fine, tho)
