### ISSUE TITLE
"Cite this page"

### ISSUE THREAD

**Issue by halfempty** [stillmuseum/worksonpaper#116]

**Comment by halfempty** [comment]
@swambold6 Here's what I have happening so far (the URL is being customized):

![image](https://cloud.githubusercontent.com/assets/775543/21408738/3e194576-c79c-11e6-9caf-766a5cf7f0f5.png)

Can you help me understand how the page title should be incorporated?

**Comment by swambold6** [comment]
@halfempty Example for this page:
http://pubs.clyffordstillmuseum.org/worksonpaper/how-to-render-the-sublime/

Chicago

Failing, Patricia. “Rendering the Sublime.” In Clyfford Still: The Works on Paper. Denver: Clyfford Still Museum Research Center, 2016. http://pubs.clyffordstillmuseum.org/worksonpaper/how-to-render-the-sublime/.

MLA

Failing, Patricia. “Rendering the Sublime.” Clyfford Still: The Works on Paper. Denver: Clyfford Still Museum Research Center, 2016. 3 Jan. 2017 <http://pubs.clyffordstillmuseum.org/worksonpaper/how-to-render-the-sublime/>.

**Comment by swambold6** [comment]
Failing wrote the essay, and nothing.

The other three wrote everything else, and not the essay.

Dean wrote the acknowledgments.

**Comment by halfempty** [comment]
@swambold6 Take a look? Also, should the page titles be incorporated somehow, especially on the Essay?

Homepage, full credit:
http://pubs.clyffordstillmuseum.org/worksonpaperdev/

Essay, only Patricia:
http://pubs.clyffordstillmuseum.org/worksonpaperdev/how-to-render-the-sublime/

Acknowledgments, only Dean:
http://pubs.clyffordstillmuseum.org/worksonpaperdev/acknowledgments/

All others, no Patricia:
http://pubs.clyffordstillmuseum.org/worksonpaperdev/introduction/

**Comment by swambold6** [comment]
@halfempty I'm confused about your comment about the page titles. The example I provide above includes them:

Chicago

Failing, Patricia. “Rendering the Sublime.” In Clyfford Still: The Works on Paper. Denver: Clyfford Still Museum Research Center, 2016. http://pubs.clyffordstillmuseum.org/worksonpaper/how-to-render-the-sublime/.

MLA

Failing, Patricia. “Rendering the Sublime.” Clyfford Still: The Works on Paper. Denver: Clyfford Still Museum Research Center, 2016. 3 Jan. 2017 http://pubs.clyffordstillmuseum.org/worksonpaper/how-to-render-the-sublime/.

**Comment by halfempty** [comment]
@swambold6 My mistake! Okay, done
