### ISSUE TITLE
[today’s date] in citations

### ISSUE THREAD

**Issue by halfempty** [stillmuseum/worksonpaper#117]

**Comment by halfempty** [comment]
@swambold6 How's this?

http://pubs.clyffordstillmuseum.org/worksonpaperdev/acknowledgments/

**Comment by halfempty** [comment]
@swambold6 Ps. I've gone ahead and published this change to static. If it looks good to you, feel free to close this ticket

**Comment by swambold6** [comment]
@halfempty This is done, right?
