### ISSUE TITLE
Object Lightboxes

### ISSUE THREAD

**Issue by halfempty** [stillmuseum/worksonpaper#13]
@swambold6 Lots of related Issues open here, but am going ahead and starting a new one for the "lightbox on lightbox" and "image background color" questions.

Here's a test, for discussion:
http://pubs.clyffordstillmuseum.org/worksonpaperdev/the-figure/

So far VERY RUDIMENTARY, but we are now opening up the two lightboxes.

**Comment by swambold6** [comment]
[20160912_WorksOnPaper.pdf](https://github.com/stillmuseum/worksonpaper/files/470037/20160912_WorksOnPaper.pdf)

Mock-ups of object views: original, w/ transparent background, and with #aaaaaa background.

**Comment by swambold6** [comment]
For my part, I like the #aaaaaa background. Going to explore some ideas for reinforcing the look as a modal window. (Have a bunch of meetings this morning...probably not available until noon.)

**Comment by swambold6** [comment]
Is this possible?

![screen shot 2016-09-13 at 8 50 53 am](https://cloud.githubusercontent.com/assets/7491703/18478649/3e2c9988-798f-11e6-89fc-81281097d787.png)

**Comment by halfempty** [comment]
@swambold6 Short answer: Yes, I think so.

**Comment by halfempty** [comment]
@swambold6 Please put the InDesign version of this design in the dropbox. Thank you!

**Comment by swambold6** [comment]
@halfempty Final images for Gallery 3: The Figure are here:

/Users/sarah/Dropbox (ClyffordStillMuseum)/Works on Paper Digital Catalogue/Object Images/20160923 Figure Gallery

(Tombstone spreadsheet is included in the same location.)

**Comment by swambold6** [comment]
@halfempty Will each object have a permalink?
