### ISSUE TITLE
Intro - Intro - Intro

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/worksonpaper#15]
@halfempty I need an opinion...

The way the outline is currently, we have three introductions: 1) the introduction to the publication; 2) the introduction to the exhibition; 3) the first gallery (The Draftsman), which is essentially another introduction.

I'm wondering what your thought is about having the link to Exhibition go to The Draftsman (in the same way that on the CSM website each main nav item goes to the first child ... What's On goes to Exhibitions).

Any thoughts?

**Comment by halfempty** [comment]
@swambold6 This is one that probably needs to be discussed verbally, eh? I don't have a full sense of the factors at play, though happy to be a sounding-board.

**Comment by halfempty** [comment]
![image](https://cloud.githubusercontent.com/assets/775543/19215340/f8171118-8d60-11e6-904a-39d1f5ea21b1.png)

**Comment by swambold6** [comment]
Deleted Exhibition Page.
