### ISSUE TITLE
The Figure Gallery / objects are misordered

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/worksonpaper#16]
@halfempty Not sure if this has been touched yet, or not, but the objects are not pulling correctly for The Figure Gallery...

These images should appear under the first paragraph of text:

![screen shot 2016-09-26 at 3 22 27 pm](https://cloud.githubusercontent.com/assets/7491703/18852311/205d452e-83fd-11e6-81f3-61a052810491.png)
![screen shot 2016-09-26 at 3 22 39 pm](https://cloud.githubusercontent.com/assets/7491703/18852314/2601ce5a-83fd-11e6-94dd-02dfa11c36ab.png)

**Comment by halfempty** [comment]
@swambold6 I added a new "section" that pulls in Objects from the set "The Figure." So that's displaying now. It's pulling in some others, though.

How's the spreadsheet on this subject? Canonical?

**Comment by swambold6** [comment]
@halfempty Got it. The spreadsheet was wrong. It's been corrected, so a new import should do it.

Though, does this mean that the "Objects" associated with the first bit of content/text (before the sections) does not do anything? (I was set to Figure before, no?)

![screen shot 2016-09-26 at 4 24 14 pm](https://cloud.githubusercontent.com/assets/7491703/18854011/b26862a2-8405-11e6-80c1-31db9a15bd67.png)

**Comment by halfempty** [comment]
@swambold6 I reimported and it seems to have worked correctly.

Re: Fields. You're right, I had specified that field for this purpose. But just creating a new section works w/o additional coding, so I'm going to switch them all over to that.

Going to close this ticket.
