### ISSUE TITLE
Link to Introduction goes to The Draftsman

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/worksonpaper#17]
@halfempty Can't figure out how to fix this...the link for Introduction (both on the home page and in the nav TOC) goes to The Draftsman. ?

**Comment by halfempty** [comment]
@swambold6 For me it's going to Exhibition (??)

**Comment by swambold6** [comment]
@halfempty Nevermind. I figured it out. (The slug for The Draftsman was Introduction.) Not sure how you're being directed to Exhibition, tho...?
