### ISSUE TITLE
Within iFrame, open Photoswipe on Load

### ISSUE THREAD

**Issue by halfempty** [stillmuseum/worksonpaper#19]

**Comment by halfempty** [comment]
All right, I believe I've got this working! Thumbnails now open up the lightbox, which contains an iframe, which contains PhotoSwipe... Take a look?

http://pubs.clyffordstillmuseum.org/worksonpaperdev/the-figure/

**Comment by halfempty** [comment]
@swambold6 All right, I believe I've got this working! Thumbnails now open up the lightbox, which contains an iframe, which contains PhotoSwipe... Take a look?

http://pubs.clyffordstillmuseum.org/worksonpaperdev/the-figure/

**Comment by swambold6** [comment]
@halfempty Looks good!

I see a slight shift in tone between the image and the modal background. Anything I can adjust on my end to improve that?

![screen shot 2016-09-29 at 8 54 12 am](https://cloud.githubusercontent.com/assets/7491703/18959174/757d719c-8622-11e6-95ce-bb5c7d184334.png)
