### ISSUE TITLE
Color shift

### ISSUE THREAD

**Issue by halfempty** [stillmuseum/worksonpaper#24]
**@swambold6 says:**

> I see a slight shift in tone between the image and the modal background. Anything I can adjust on my end to improve that?

![screen shot 2016-09-29 at 8 54 12 am](https://cloud.githubusercontent.com/assets/7491703/18959174/757d719c-8622-11e6-95ce-bb5c7d184334.png)

**Comment by halfempty** [comment]
@swambold6 I'm not sure there's anything we can do about that, exactly. However, I do think it would help if we cropped the images in closer, so there's as little JPG grey as necessary.

**Comment by swambold6** [comment]
@halfempty I've been cropping everything closer. Can you add some padding around the images in the lightbox view? 30 pixels should probably do it. Thanks!

**Comment by halfempty** [comment]
Done
