### ISSUE TITLE
Setup Google Analytics

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/worksonpaper#28]
Set up for static site.
Make sure GA tracks subdomain.
Figure out how to exclude CSM's IP address.

**Comment by halfempty** [comment]
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-29830735-3', 'auto');
  ga('send', 'pageview');

</script>

**Comment by halfempty** [comment]
Done
