### ISSUE TITLE
Paragraph break within footnote 30

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/worksonpaper#31]
Footnote 30 is meant to appear like this (we need a paragraph break within the footnote if possible):

The Colville Reservation was established in 1872. People from twelve different tribal groups were ultimately assigned to the reservation. In 1912–13, the Colville Indian Agency Headquarters was moved to the small town of Nespelem, Washington, a venue for Fourth of July celebrations that included weeklong, intertribal pow-wows attended by native people in new and heirloom regalia. Construction of the Columbia River’s Grand Coulee Dam, which joins reservation land on its east end, began in 1933. Its consequences for reservation culture were severe: no provisions for a fish ladder were made for Grand Coulee, and by 1938, the progress of the dam had stopped all salmon from migrating upriver. 

Still and Griffin were headquartered in Nespelem in 1936, and in 1937 established a Washington State Summer Art Colony there. The colony, designed primarily to attract art teachers and advanced students during their summer breaks, continued until 1940. Griffin taught portraiture. Still served as colony instructor in 1937 and 1938, in charge of landscape painting and composition.

**Comment by swambold6** [comment]
on this page: http://pubs.clyffordstillmuseum.org/worksonpaperdev/how-to-render-the-sublime/

**Comment by halfempty** [comment]
Done
