### ISSUE TITLE
Margins and column widths

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/worksonpaper#36]
@halfempty I don't think we have an issue open for this, but we discussed it right? (Full screen desktop columns are too wide; need to be using fixed widths with divs, or something like that...?)

:)

**Comment by swambold6** [comment]
Another example of column / margin issues:
http://pubs.clyffordstillmuseum.org/worksonpaperdev/the-figure/

Text should not extend beyond three columns wide if possible.
![screen shot 2016-10-07 at 3 46 50 pm](https://cloud.githubusercontent.com/assets/7491703/19206336/53ce3f66-8ca5-11e6-896e-fec6bb377b20.png)

**Comment by halfempty** [comment]
@swambold6 I put in a bunch of breakpoints for screens greater than 1800px, so you should see a big difference on your desktop. I may have missed some things, so if you see anything out of whack, please flag it.
