### ISSUE TITLE
Location in object tombstones needs a comma and space between city and state

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/worksonpaper#37]
On the tombstones for the objects, the city and state are not separated by a comma + space.

Example PP-6:
PullmanWashington

Should be:
Pullman, Washington

**Comment by halfempty** [comment]
@swambold6 This will be fixed by renaming the terms via WP, post-import.

**Comment by halfempty** [comment]
This is actually a development issue.

**Comment by halfempty** [comment]
@swambold6 Okay, taking another look at this. I'd like for us to remove the commas from the Locations column on the spreadsheet. I think they're confusing the import and causing this issue.

I've put into the Dropbox a "v6" copy of the spreadsheet, with the adjusted Location column. Could you please copy this column into your copy of the spreadsheet? When done, re-assign this to me.

Thank you!

**Comment by swambold6** [comment]
@halfempty Can this be done today / tonight?

**Comment by halfempty** [comment]
Fixed
