### ISSUE TITLE
Pressbooks

### ISSUE THREAD

**Issue by halfempty** [stillmuseum/worksonpaper#4]
@swambold6 Apparently this is a WP -> PDF system.

https://pressbooks.com/blog/free-at-last-pressbooks-plugin-is-now-freeopen-source-software/

https://wordpress.org/plugins/pressbooks-mpdf/

**Comment by swambold6** [comment]
@halfempty Interesting. Says can't use for an existing WP site...a problem for us?

Also, help me understand what this does and what PrinceXML does. Says you need both.

**Comment by halfempty** [comment]
@swambold6 Yes, I think it makes *only the book,* so the scenario would be to re-import/input the book data in whatever specific way it needs. (It may be possible to start with Pressbooks instance and then evolve to a website, but for a first project I would keep them separate.)

While Prince does the actual PDF generation, my understanding is you need something to setup  and manage the book -- what order things are in, which templates they use, etc. That's the custom piece the Getty built in-between Middleman and Prince, I think. Pressbooks seems to be that for WP + Prince.

**Comment by swambold6** [comment]
@halfempty Thanks for the explanation. I sort of understand. 

So for the PDF, we'd set up a new WP with Pressbooks in addition to the WP installation for the actual website?

Diagrams and flow charts are always helpful... :) Either way, sounds like good news.

**Comment by halfempty** [comment]
@swambold6 This has its own project now, so closing
