### ISSUE TITLE
buttons for next page at bottom of current page

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/worksonpaper#44]
Wish list item...

I would love to have buttons for the next page at the bottom of the current page (a la Converse microsite). This is not in the mockups, I never designed it. So not your problem, Marty. (Reminder to myself.)

**Comment by swambold6** [comment]
In new INDD doc (Desktop page 2)

20161021_WorksOnPaper.indd

**Comment by halfempty** [comment]
Duplicate of #86
