### ISSUE TITLE
GA: Figure out how to exclude CSM's IP address.

### ISSUE THREAD

**Issue by halfempty** [stillmuseum/worksonpaper#52]

**Comment by halfempty** [comment]
https://support.google.com/analytics/answer/1034840?hl=en

**Comment by swambold6** [comment]
@halfempty I *think* I have this figured out. Setting up the filter was the easy bit, but I can't tell if I have to "activate" the filter. It appears that I don't...once it's set up it starts filtering. But if you have a moment to look at it, I'd appreciate the validation.

**Comment by halfempty** [comment]
@swambold6 Yes. I followed the instructions under "Make sure the filter works" and am getting the desired result: "Hit dropped by filter Excluding internal traffic". So, it works!
