### ISSUE TITLE
HRs on Essay

### ISSUE THREAD

**Issue by halfempty** [stillmuseum/worksonpaper#58]
@swambold6 Should these be styled? Flat grey?

![image](https://cloud.githubusercontent.com/assets/775543/19258047/3ed610d8-8f3a-11e6-91e3-037c6f7e2353.png)

**Comment by swambold6** [comment]
Flat gray, but is there a way to add some space below it, before the section title? I tried adding non breaking space and a paragraph break, but it doesn't work (not surprisingly).

![screen shot 2016-10-19 at 9 39 23 am](https://cloud.githubusercontent.com/assets/7491703/19525996/291c35f4-95e0-11e6-8fcf-4dea41203946.png)
(from InDesign)

**Comment by halfempty** [comment]
Done
