### ISSUE TITLE
Logo swap

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/worksonpaper#63]
Please swap the CSM logo in the footer with the CSM Research Center logo. Two file options located here: /Users/sarah/Dropbox (ClyffordStillMuseum)/Works on Paper Digital Catalogue/Logos

**Comment by halfempty** [comment]
@swambold6 This logo is all alias-y, like so:

![image](https://cloud.githubusercontent.com/assets/775543/19546889/dedc75a2-9658-11e6-9ec3-73f7b34ee888.png)

Do we have vector?

**Comment by halfempty** [comment]
@swambold6 I've put in the copy we have: 

![image](https://cloud.githubusercontent.com/assets/775543/19546923/2d42dae2-9659-11e6-9524-db7125816c60.png)

**Comment by swambold6** [comment]
EPS added here: /Users/sarah/Dropbox (ClyffordStillMuseum)/Works on Paper Digital Catalogue/Logos

CSMRC_Logo_FINAL.eps

**Comment by halfempty** [comment]
Done
