### ISSUE TITLE
Footer update

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/worksonpaper#64]
Update content in footer with this info:

Published by the Clyfford Still Museum Research Center on the occasion of the exhibition Clyfford Still: The Works on Paper, presented at the Clyfford Still Museum, Denver, Colorado (Oct 14, 2016–Jan 15, 2017)

Copyright © 2016 by Clyfford Still Museum
All rights reserved. Unless otherwise noted, all works by Clyfford Still are © 2016 City and County of Denver, courtesy Clyfford Still Museum / Artists Rights Society (ARS), New York.

Downloads | Privacy Policy | Terms of Use

**Comment by halfempty** [comment]
Done 

(Excepting Downloads and Terms of Use, which are their own thing)
