### ISSUE TITLE
Update Homepage content

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/worksonpaper#65]
For Introduction:

Clyfford Still (1904–1980) may have explored the potential of drawing more than any other artist of his time. The sheer volume (more than 2,300) and variety of Still’s works on paper reveal the centrality of drawing within ...

For Essay:

Among Clyfford Still’s remarkable accomplishments was his success in setting conditions for the reception of his work. Dealers and museums—even New York’s venerable Metropolitan Museum of Art—bowed to his dictates ...

![screen shot 2016-10-19 at 9 29 53 am](https://cloud.githubusercontent.com/assets/7491703/19525579/a70e2de8-95de-11e6-96f7-e95981fe0858.png)

**Comment by halfempty** [comment]
Done
