### ISSUE TITLE
Object spreadsheet available for upload

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/worksonpaper#70]
Dropbox (ClyffordStillMuseum)/Works on Paper Digital Catalogue/20161019_WOP_DigitalPub_WorkData_v5_LW_SW_FINAL.xlsx

Are you able to import this afternoon?

**Comment by halfempty** [comment]
@swambold6 Imported!

One question I had is around the column, "Category." This maps to our "Sets," which associate objects with sections of pages.

One question is I noticed that a number of objects don't have an entry in Category, and not all the Category phrases appear to match with page sections. Is this okay / the way it's supposed to be?

Also, I noticed a couple of page sections where I didn't find a Category. These were:
Recipe Card Pastels
The Richmond Oils on Paper

**Comment by swambold6** [comment]
@halfempty I think I know what happened... Didn't we have a rule that if they didn't have a set/category, they were placed at the top of the page just below the text? On this page, which had been done for a while, the female nudes came after The Figure text, and before Nespelem:

http://pubs.clyffordstillmuseum.org/worksonpaperdev/the-figure/

Right?

**Comment by halfempty** [comment]
@swambold6 We do still need them organized into "sets" to pull them onto the page. Can you add to Category entries for these, possibly reflecting the page/room names? Like, "The Figure", etc? 

(Makes sense?)

**Comment by swambold6** [comment]
Makes sense. Add them to the spreadsheet for reupload, or manually open them as assign?

**Comment by halfempty** [comment]
@swambold6 Whichever you prefer. I will be able to reupload tonight, though probably not during the day.

**Comment by swambold6** [comment]
@halfempty I think I'll do manual and see how that goes...

In the upload last night, this one lost its image. Filename probably didn't match:
http://pubs.clyffordstillmuseum.org/worksonpaperdev/wp-admin/post.php?post=2522&action=edit

Would you do me a favor and find/resolve?

**Comment by swambold6** [comment]
@halfempty Actually it might be easier to do a reimport... Is it something I can do without screwing things up?

**Comment by swambold6** [comment]
@halfempty Nevermind...I'm working on all of this. No need to respond or do my favor from above.

**Comment by halfempty** [comment]
@swambold6 I don't see that image in the DropBox btw
