### ISSUE TITLE
Images available for upload

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/worksonpaper#71]
Dropbox (ClyffordStillMuseum)/Works on Paper Digital Catalogue/Object Images/20161019 IMAGES

Gallery 2 will need to be replaced with clipped/cropped images.
Gallery 3 is already in WP and good to go.
Gallery 4 I will add to this folder as soon as I can reduce the file sizes and save as JPGs (likely tomorrow, so does not need to be included in the 10/19 deadline).

**Comment by halfempty** [comment]
Done!
