### ISSUE TITLE
Turn off flickety

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/worksonpaper#73]
this page: http://pubs.clyffordstillmuseum.org/worksonpaperdev/introduction/

(and probably one more...stay tuned...)

**Comment by halfempty** [comment]
@swambold6 

Done.

There are separate fields for "Installation images," which have Flickety, and "Featured Images," which don't. The "Featured Images" fieldset is a little bit lower down on the Edit page.

**Comment by swambold6** [comment]
Got it. Thanks!
