### ISSUE TITLE
Thumbnails not rendering so well

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/worksonpaper#77]
Just noticing some pixelation in the rendering of the thumbnails. Example here:

![screen shot 2016-10-20 at 10 36 30 am](https://cloud.githubusercontent.com/assets/7491703/19568996/2194a718-96b1-11e6-9a91-372dec2eda33.png)

Any idea what's causing that?

**Comment by halfempty** [comment]
@swambold6 It has to do with responsive. I've put in sizes for iPad (1024) and 1800+, but I think I should put in an intermediate as well.

Btw what's your window size when you see this? > 1800? or < 1800?

**Comment by swambold6** [comment]
1600ish.

**Comment by halfempty** [comment]
Fixed
