### ISSUE TITLE
Title Image on Homepage

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/worksonpaper#78]
Dean asks, can the main image (the purple pastel) on the homepage load faster?

**Comment by halfempty** [comment]
@swambold6 What size screen is Dean using? (There's different images used there based on breakpoints. I can tweak the one for his size, making it smaller.)

**Comment by swambold6** [comment]
@halfempty He's on a 21.5-in iMac.

**Comment by halfempty** [comment]
@swambold6 Okay, tweaked this. Smaller file now, will load faster.
