### ISSUE TITLE
Tweak desktop breakpoints

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/worksonpaper#79]
@halfempty All of a sudden this morning, everything got bigger on my screen than it has been. It looks like I'm zoomed into 200%. Wondering what may have happened...?

**Comment by halfempty** [comment]
@swambold6 I didn't change the CSS in that time. Could it be your browser's zoomed-in somehow?

**Comment by swambold6** [comment]
@halfempty It is not zoomed in. Is it possible you changed them the night before, and at some point a refresh finally grabbed the new code? Regardless, it's still screwed up...

![screen shot 2016-10-24 at 9 11 15 am](https://cloud.githubusercontent.com/assets/7491703/19651358/c24e2d44-99c9-11e6-9f4c-7764ad0802dc.png)

**Comment by swambold6** [comment]
@halfempty Nearly everything is too big...the breadcrumbs bar, the paragraph size, the H2 sizes. Caption size looks good to me.

![screen shot 2016-10-24 at 9 13 15 am](https://cloud.githubusercontent.com/assets/7491703/19651440/137d1c52-99ca-11e6-9b96-cde096a2edd7.png)

**Comment by halfempty** [comment]
@swambold6 There's a breakpoint at 1800. These sizes are from the InDesign... right?

**Comment by swambold6** [comment]
@halfempty I don't understand the question.

**Comment by swambold6** [comment]
@halfempty Regardless, the break point needs to be adjusted. It's too big on this screen. What do you suggest.

**Comment by swambold6** [comment]
@halfempty Is this issue a moot point? Should we close?

**Comment by halfempty** [comment]
Let's close.
