### ISSUE TITLE
Disable right-click on Object pages

### ISSUE THREAD

**Issue by halfempty** [stillmuseum/worksonpaper#8]
Can we do it?

**Comment by swambold6** [comment]
Still a concern.

**Comment by halfempty** [comment]
@swambold6 I believe I've got this working. No right-click over Photoswipe... Give it a test?

http://pubs.clyffordstillmuseum.org/worksonpaperdev/the-figure/

**Comment by swambold6** [comment]
@halfempty FANTASTIC!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

THANK YOU!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
