### ISSUE TITLE
Main image doesn't load on phones

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/worksonpaper#81]
@halfempty The main image doesn't load when viewing on my phone.

**Comment by halfempty** [comment]
@swambold6 

It's showing on my iPhone 5, and in the simulator. 

What's your model? iPhone 6?

**Comment by swambold6** [comment]
@halfempty I have an iphone 6. Let me know if you want screenshots.

**Comment by halfempty** [comment]
@swambold6 From my cousin, iPhone 6:

![image](https://cloud.githubusercontent.com/assets/775543/19705959/004ebc42-9ad5-11e6-987b-f860240e299a.png)

**Comment by swambold6** [comment]
@halfempty Loading for me now, too! Hooray!
