### ISSUE TITLE
Surface lending credit

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/worksonpaper#82]
These two works (and only these) have lending credits:

http://pubs.clyffordstillmuseum.org/worksonpaperdev/the-richmond-oils-on-paper/#object-phx-13
http://pubs.clyffordstillmuseum.org/worksonpaperdev/san-francisco/#object-fa1976-92

It can go at the bottom of the tombstone information, before the extended label. So for example:

---

PH-479

1948
gouache on paper	
28 7/8 x 22 inches (73.3 x 55.9 cm)
San Francisco, California
Collection of the New Jersey State Museum, Trenton, New Jersey. Gift of Mr. and Mrs. L.B. Wescott.

Exhibited at the Marlborough-Gerson Gallery, New York, 1969–70.

**Comment by halfempty** [comment]
Done
