### ISSUE TITLE
More changes to home page

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/worksonpaper#83]
I added back Exhibition and made the sections submenu items. (I actually added another link to the page The Draftsman and relabeled it Exhibition because Exhibition won't be a page, but will direct to the first child, which is The Draftsman. Feel free to do that the correct way and get rid of my hack.)

We need to move Failing's essay between the Introduction and the Exhibition. (Order should be Introduction — How to Render the Sublime — Exhibition (+ sections) — Acknowledgments — About.

Also, in the weird sizing up / breakpoints problem that occurred this morning, it seems the typestyles were affected. TOC is MUCH bigger than it was; Introduction and How to Render the Sublime are larger than Exhibition, Acknowledgments, and About.

![screen shot 2016-10-21 at 2 52 41 pm](https://cloud.githubusercontent.com/assets/7491703/19611245/ff7f15d0-979d-11e6-899e-3a41c3770932.png)

**Comment by halfempty** [comment]
Done
