### ISSUE TITLE
new spreadsheet for data import

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/worksonpaper#84]
I've updated the last version of the spreadsheet:
20161019_WOP_DigitalPub_WorkData_v5_LW_SW_FINAL.xlsx

A few things to note:

There is a new column called display media. This combines columns for work material names 1 and 2 and work material support. I'd not been given this data before--didn't know it existed in this format. Display Media needs to be what is displayed in the object text. you can still use the other fields for the tags.

There is a new column called Original Text. You do not need to do anything with this text. I'm preserving the original text in case something that I've edited needs to be restored.

Everything should be ready for a new import and it should work beautifully!

**Comment by swambold6** [comment]
...fingers crossed.

**Comment by halfempty** [comment]
Done
