### ISSUE TITLE
Next page buttons

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/worksonpaper#86]
There is an updated INDD doc with updates on Desktop Page 1 (rollover color for text links), and Desktop Page 2 (next page button and a rollover state for the button).

I'd like for the button to have the text for the next section in the button.

**Comment by swambold6** [comment]
@halfempty Spelled out. Let me know if I forgot anything.

![screen shot 2016-10-28 at 12 00 03 pm](https://cloud.githubusercontent.com/assets/7491703/19816813/0f38fd70-9d06-11e6-8a3e-e5f91740451a.png)

**Comment by halfempty** [comment]
Done

**Comment by swambold6** [comment]
@halfempty Are these supposed to display as buttons? 

![screen shot 2016-10-31 at 1 38 47 pm](https://cloud.githubusercontent.com/assets/7491703/19868786/40b18aaa-9f6f-11e6-9c29-a19628c6464b.png)

**Comment by halfempty** [comment]
@swambold6 Refresh you cache. ;)

**Comment by swambold6** [comment]
@halfempty Hooray! Beautiful!

![screen shot 2016-10-31 at 2 08 55 pm](https://cloud.githubusercontent.com/assets/7491703/19869812/7492e6e4-9f73-11e6-9171-6bfaf8ce1e88.png)
