### ISSUE TITLE
CSMRC logo

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/worksonpaper#90]
@halfempty Dean would like the CSMRC logo to be black and white, as opposed to white and transparent. What were your settings for saving the EPS? I can format and resend.

**Comment by halfempty** [comment]
@swambold6 It's an SVG

**Comment by swambold6** [comment]
@halfempty I don't know how to make an SVG. There's a new B&W jpg in the Logos folder on Dropbox: CSMRC_Logo_BW.jpg

Feel free to make another one from the EPS already in the file.

**Comment by halfempty** [comment]
@swambold6 I'magonna put some white space around this, cool?

**Comment by swambold6** [comment]
@halfempty yes please.

**Comment by halfempty** [comment]
@swambold6 Yeesh, i still don't know about this...

![image](https://cloud.githubusercontent.com/assets/775543/19699821/6eeb0a90-9aba-11e6-92b6-8c5d77f4b701.png)

**Comment by halfempty** [comment]
@swambold6 Can I re-gigger this? Would Dean be cool with a white-on black?

**Comment by halfempty** [comment]
@swambold6 How about something along these lines...

![image](https://cloud.githubusercontent.com/assets/775543/19700607/931efedc-9abd-11e6-94eb-8fb7f6639c3f.png)

**Comment by swambold6** [comment]
@halfempty Lemme try something... stay tuned...

**Comment by swambold6** [comment]
@halfempty Try this file on the light green.
https://www.dropbox.com/s/rj7lf1jc9b0ebdw/CSMRC_Logo_BWtransparent.gif?dl=0

**Comment by halfempty** [comment]
@swambold6 I'm kinda diggin' these two bands. What about softening the contrast:

![image](https://cloud.githubusercontent.com/assets/775543/19704780/c00aa6e2-9ace-11e6-8e6e-772cd9886949.png)

This gets us an echo of the top-bar.

**Comment by swambold6** [comment]
@halfempty The gray is much more elegant, but it doesn't solve it... Dean specifically asked me to use the black and white on the logo. Any luck with the file I provided? Throw it up on the gray if you like, just to see what the quality of it is. (I don't know how to save a SVG out of Photoshop...)

**Comment by halfempty** [comment]
@swambold6 Would black on green solve it, tho?

I can play the designer on this one and say "that looks bad. this looks better," if you need it.

**Comment by swambold6** [comment]
@halfempty When he asked for it to be B&W, he added that the logo is based on a specific painting. He's left for the day otherwise I'd ask him to pop over. I think it was a fairly serious request tho...when he's convince-able he usually says, "think about it," but for this one, he was more like, "You altered the logo, fix it."

**Comment by halfempty** [comment]
@swambold6 Back to black then:

![image](https://cloud.githubusercontent.com/assets/775543/19706364/1cb50240-9ad7-11e6-9903-a7ca5f72f593.png)

If you want me to design it, then here it is, let's move on. 
But if you want it some other way, please do a mockup and I will be happy to implement.

**Comment by swambold6** [comment]
@halfempty 

![screen shot 2016-10-25 at 4 32 12 pm](https://cloud.githubusercontent.com/assets/7491703/19706695/8bbfda18-9ad0-11e6-8db4-6c57be96784b.png)

Logo here: https://www.dropbox.com/s/rj7lf1jc9b0ebdw/CSMRC_Logo_BWtransparent.gif?dl=0

Let me know if the logo is pixelated, and I will try a different format.

**Comment by halfempty** [comment]
Done
