### ISSUE TITLE
location tags

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/worksonpaper#96]
@halfempty I've edited quite a few objects manually today, and I've just noticed that any one that has been updated manually will have incorrect location tags (same comma issue as before). I don't know how to resolve this. A reimport is not an option.

**Comment by halfempty** [comment]
@swambold6 Locations are simply a kind of tag. They can be sorted-out via the Objects -> Locations screen.

Give me an example of one that's gotten messed?

**Comment by swambold6** [comment]
@halfempty Send me screenshots or let's do a video chat so you can show me. When I try to correct it through the Locations panel in the Object screen it doesn't work.

http://pubs.clyffordstillmuseum.org/worksonpaperdev/the-landscape/#object-1-2011-2957

**Comment by halfempty** [comment]
@swambold6 Ok yeah, I see what you're talking about. Let me see what I can do...

**Comment by halfempty** [comment]
@swambold6 These are updated, should be improved.

**Comment by halfempty** [comment]
Done
