### ISSUE TITLE
Gallery map for exhibition pages

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/worksonpaper#97]
@halfempty I've added a line drawing map for Gallery 1 here:
/Users/sarah/Dropbox (ClyffordStillMuseum)/Works on Paper Digital Catalogue/Graphics/Map_Gallery1.jpg

Can you put this in the sidebar area (where the caption would be) and let me know. I need to see how it looks before I move forward.

![screen shot 2016-10-24 at 1 43 54 pm](https://cloud.githubusercontent.com/assets/7491703/19661159/db8def9e-99ef-11e6-9e5d-3dfceaea86cb.png)

**Comment by dabernathy89** [comment]
@halfempty hey - do you know what the timeline is for this?

**Comment by halfempty** [comment]
@dabernathy89 writing-up a note on this now

**Comment by halfempty** [comment]
@dabernathy89 Dan, can I bring you in on this one? Sarah would like to try putting little maps on some of the pages. 

So... On some pages, such as the homepage, we use an Advanced Custom Fields field called "Featured Image" (NOT the WP Core "Featured Image") to specify an image for the large area at the top of the page. In this case, as a set of `div`s, most directly one called `captionpadding`, is generated to hold a caption.

On other pages, we use an ACF field called "Installation Views" to populate the large area.

The idea of this enhancement is, on the "Installation Views" pages, to allow the addition of an image into the caption column. This will mean adding a new Image field to the "Installation Views" set, allowing for the image to be specified. Then updating the theme to look for this field and, if found, assemble the caption divs, with the image inside.

Does this make sense? Here's an image to work with while testing:

![map_gallery1](https://cloud.githubusercontent.com/assets/775543/20364889/812110e0-ac0a-11e6-945c-81a016e0d25c.jpg)

Also, it would be good to do the theme work on this in its own branch, in case there are other hot-fixes that need to be applied while this is in-progress.

As for timelines, let's ask @swambold6.

**Comment by dabernathy89** [comment]
I think early next week is doable for this.

**Comment by dabernathy89** [comment]
Hey sorry this one is just getting done - quick question though. What about just having a general content section to pop into the sidebar there (if set)? Would there be a situation where multiple images, or text would need to appear there?

**Comment by halfempty** [comment]
@dabernathy89 However you'd prefer to develop it. However, there's no plan to put any other content into this spot. And after this round of changes this website will probably "lock."

**Comment by dabernathy89** [comment]
@halfempty Gotcha - well here it is with just a generic content WYSIWYG field:

http://pubs.clyffordstillmuseum.org/worksonpaperdev/the-figure/

**Comment by halfempty** [comment]
@swambold6 Do you have the map graphics for the other rooms?

**Comment by halfempty** [comment]
@dabernathy89 We need to update the styling for the < 764px breakpoint

**Comment by swambold6** [comment]
@dabernathy89 @halfempty I'll work on finishing up the graphics today. Do you want to work on the phone breakpoint?

**Comment by dabernathy89** [comment]
I'll take care of this ASAP as well.

**Comment by dabernathy89** [comment]
For < 764, do we want to center the image or have it left aligned? Either way, I've changed it to not stretch to 100% width:

http://pubs.clyffordstillmuseum.org/worksonpaperdev/the-figure/

**Comment by halfempty** [comment]
@dabernathy89 I don't have a super strong feeling about it, but would probably go for centered.

Can we put some margin or padding at the top to move it away from the carousel dots?

**Comment by dabernathy89** [comment]
centered and added some top margin on mobile

**Comment by halfempty** [comment]
@dabernathy89 Looks good! 

@swambold6, this one's over to you, as you're getting the graphics approved. When you have them, please send to me!

**Comment by swambold6** [comment]
@dabernathy89 @halfempty Graphics here:

https://www.dropbox.com/sh/q65ht9u0tynisn5/AAAOnsbXtI9Ig75ExJ3WDnpXa?dl=0

**Comment by halfempty** [comment]
@swambold6 Done! Take a look, confirm and close if good?
